<a href="https://colab.research.google.com/github/Snehal1123/Education/blob/Branch1/Error_Optimaxation_Ads.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv("/content/Advertising.csv")

In [ ]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
x = df[["TV","Radio","Newspaper"]].values

In [ ]:
x

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [ ]:
y = df[["Sales"]].values

In [ ]:
y

array([[22.1],
       [10.4],
       [12. ],
       [16.5],
       [17.9],
       [ 7.2],
       [11.8],
       [13.2],
       [ 4.8],
       [15.6],
       [12.6],
       [17.4],
       [ 9.2],
       [13.7],
       [19. ],
       [22.4],
       [12.5],
       [24.4],
       [11.3],
       [14.6],
       [18. ],
       [17.5],
       [ 5.6],
       [20.5],
       [ 9.7],
       [17. ],
       [15. ],
       [20.9],
       [18.9],
       [10.5],
       [21.4],
       [11.9],
       [13.2],
       [17.4],
       [11.9],
       [17.8],
       [25.4],
       [14.7],
       [10.1],
       [21.5],
       [16.6],
       [17.1],
       [20.7],
       [17.9],
       [ 8.5],
       [16.1],
       [10.6],
       [23.2],
       [19.8],
       [ 9.7],
       [16.4],
       [10.7],
       [22.6],
       [21.2],
       [20.2],
       [23.7],
       [ 5.5],
       [13.2],
       [23.8],
       [18.4],
       [ 8.1],
       [24.2],
       [20.7],
       [14. ],
       [16. ],
       [11.3],
       [11

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Lin = LinearRegression()

In [ ]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
pred_y = Lin.predict(x)

In [ ]:
y - pred_y

array([[ 0.87902791],
       [-0.86824775],
       [ 1.50379103],
       [-0.81244651],
       [ 2.25586315],
       [-3.15633677],
       [ 0.5267153 ],
       [-0.07062458],
       [-0.51839603],
       [-0.18871013],
       [ 3.7472798 ],
       [-1.48400523],
       [-0.49879662],
       [ 2.95078627],
       [-0.27328852],
       [ 2.01445555],
       [ 0.22894206],
       [ 0.19785498],
       [ 0.7075602 ],
       [-0.60872794],
       [-1.49794066],
       [-0.60414656],
       [-1.46177654],
       [ 1.62778928],
       [ 0.32854579],
       [-2.31996936],
       [-0.54479137],
       [ 1.40783698],
       [-2.17865408],
       [ 0.30528933],
       [-2.21492832],
       [-0.74683045],
       [ 3.11217449],
       [-3.8260486 ],
       [ 1.91212915],
       [-3.09407055],
       [ 1.55496506],
       [ 0.70657589],
       [ 0.2595484 ],
       [ 0.41655065],
       [-1.44712878],
       [-0.74885818],
       [-2.87494339],
       [ 1.10237228],
       [-0.25617872],
       [-0

In [ ]:
np.abs(y - pred_y).mean()

1.2363919943957848

In [ ]:
from sklearn import metrics

In [ ]:
metrics.mean_absolute_error(y , pred_y)

1.2363919943957848

**train and test the data**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.2, random_state = 0 )

In [ ]:
test_x

array([[ 69.2,  20.5,  18.3],
       [ 50. ,  11.6,  18.4],
       [ 90.4,   0.3,  23.2],
       [289.7,  42.3,  51.2],
       [170.2,   7.8,  35.2],
       [ 56.2,   5.7,  29.7],
       [  8.7,  48.9,  75. ],
       [240.1,   7.3,   8.7],
       [ 23.8,  35.1,  65.9],
       [197.6,  23.3,  14.2],
       [261.3,  42.7,  54.7],
       [ 87.2,  11.8,  25.9],
       [156.6,   2.6,   8.3],
       [187.8,  21.1,   9.5],
       [ 76.4,  26.7,  22.3],
       [120.2,  19.6,  11.6],
       [265.6,  20. ,   0.3],
       [  0.7,  39.6,   8.7],
       [ 74.7,  49.4,  45.7],
       [213.4,  24.6,  13.1],
       [287.6,  43. ,  71.8],
       [140.3,   1.9,   9. ],
       [175.1,  22.5,  31.5],
       [131.7,  18.4,  34.6],
       [ 53.5,   2. ,  21.4],
       [123.1,  34.6,  12.4],
       [165.6,  10. ,  17.6],
       [205. ,  45.1,  19.6],
       [224. ,   2.4,  15.6],
       [ 25.1,  25.7,  43.3],
       [ 67.8,  36.6, 114. ],
       [198.9,  49.4,  60. ],
       [280.7,  13.9,  37. ],
       [24

In [ ]:
test_y

array([[11.3],
       [ 8.4],
       [12. ],
       [25.4],
       [16.7],
       [ 8.7],
       [ 7.2],
       [18.2],
       [ 9.2],
       [16.6],
       [24.2],
       [10.6],
       [15.5],
       [20.6],
       [11.8],
       [13.2],
       [17.4],
       [ 1.6],
       [14.7],
       [17. ],
       [26.2],
       [10.3],
       [16.1],
       [12.9],
       [ 8.1],
       [15.2],
       [17.6],
       [22.6],
       [16.6],
       [ 8.5],
       [12.5],
       [23.7],
       [16.1],
       [21.8],
       [ 5.6],
       [ 6.7],
       [ 9.7],
       [17.9],
       [13.6],
       [ 7.2]])

In [ ]:
df.corr()      #this is a correlation matrix

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [ ]:
x = df[["TV"]].values

In [ ]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
pred_yTV = Lin.predict(x)

In [ ]:
metrics.mean_absolute_error(y, pred_yTV)

1.8305872641932412

In [ ]:
x = df[["TV" ,"Radio"]].values

In [ ]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
pred_yTVRadio = Lin.predict(x)

In [ ]:
metrics.mean_absolute_error(y, pred_yTVRadio)

1.2367636706717362